import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { createApi } from '../server/api.js';
import { newBill, calculate } from '../shared/calculations.js';

test('two-user settlement, auth boundaries, invitation claim, concurrent edits and durable history', async t => {
  const directory = mkdtempSync(`${tmpdir()}/tab-together-test-`), { api, db } = createApi(directory), app = express(); app.use('/api', api);
  const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve));
  t.after(() => { server.close(); db.close(); });
  const base = `http://127.0.0.1:${server.address().port}/api`;
  async function call(route, token, body, method = body ? 'POST' : 'GET') { const response = await fetch(`${base}${route}`, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body ? { 'Content-Type':'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: response.status, data: await response.json() }; }
  const ali = (await call('/register', null, { name: 'Ali' })).data, stranger = (await call('/register', null, { name: 'Stranger' })).data;
  assert.equal((await call('/state')).status, 401);
  const friend = (await call('/friends', ali.token, { name: 'Sara' })).data;
  await call('/profile', ali.token, { name: 'Ali', paymentDetails: 'TEST account — no real transfers' }, 'PATCH');
  let b = newBill(ali.user.id); b.title = 'Test dinner'; b.participants.push(friend.person.id); b.items = [{ id:'food', name:'Dinner', quantity:2, unitPriceCents:1500000, eligible:true, allocations:[{ personId:ali.user.id, quantity:1 }, { personId:friend.person.id, quantity:1 }] }]; b.discount = { ...b.discount, type:'percent', rate:50, eligibleCapCents:2000000 };
  let saved = (await call('/bills', ali.token, { bill:b })).data;
  assert.equal((await call('/state', stranger.token)).data.bills.length,0);
  assert.equal((await call(`/bills/${saved.id}`, stranger.token, { bill:b, version:saved.version }, 'PUT')).status,403);
  assert.equal((await call(`/bills/${saved.id}`, ali.token, { bill:b, version:999 }, 'PUT')).status,409);
  const sara = (await call('/register', null, { name:'Sara', inviteToken:friend.inviteToken })).data;
  assert.equal((await call('/state', sara.token)).data.bills.length,0, 'other participants cannot see drafts');
  assert.equal((await call('/register', null, { name:'Fake Sara', inviteToken:friend.inviteToken })).status,404);
  const published = await call(`/bills/${saved.id}/publish`, ali.token, { version:saved.version }); assert.equal(published.status,200);
  assert.equal((await call(`/bills/${saved.id}/publish`, ali.token, { version:saved.version })).status,409);
  const saraState = (await call('/state', sara.token)).data, aliState = (await call('/state', ali.token)).data;
  assert.equal(saraState.bills.length,1); assert.ok(saraState.events.length); assert.equal(aliState.debts.length,1,'payer is never billed for their own share');
  const debt = saraState.debts[0]; assert.equal(debt.amount,1000000); assert.equal(debt.creditor_id,ali.user.id);
  assert.equal((await call(`/debts/${debt.id}/action`, stranger.token, { action:'accept' })).status,403);
  assert.equal((await call(`/debts/${debt.id}/action`, sara.token, { action:'confirm' })).status,403);
  assert.equal((await call(`/debts/${debt.id}/action`, sara.token, { action:'paid' })).status,409);
  assert.equal((await call(`/debts/${debt.id}/action`, sara.token, { action:'dispute', note:'Check quantity' })).data.status,'disputed');
  assert.equal((await call(`/debts/${debt.id}/action`, sara.token, { action:'accept' })).data.status,'accepted');
  assert.equal((await call(`/debts/${debt.id}/action`, sara.token, { action:'paid', reference:'TEST-123' })).data.status,'marked_paid');
  assert.equal((await call('/state', ali.token)).data.debts.filter(d=>d.status!=='confirmed').reduce((s,d)=>s+d.amount,0),1000000,'marked-paid is still outstanding');
  assert.equal((await call(`/debts/${debt.id}/action`, ali.token, { action:'reject', note:'Not in test account' })).data.status,'accepted');
  await call(`/debts/${debt.id}/action`, sara.token, { action:'paid', reference:'TEST-456' });
  assert.equal((await call(`/debts/${debt.id}/action`, ali.token, { action:'confirm' })).data.status,'confirmed');
  assert.equal((await call(`/debts/${debt.id}/action`, ali.token, { action:'confirm' })).status,409,'duplicate confirmation rejected');
  assert.equal((await call(`/bills/${saved.id}`, ali.token, { bill:b, version:2 }, 'PUT')).status,409,'published bill locked');
  const recovered = (await call('/recover', null, { code:sara.recoveryCode })).data;
  assert.equal(recovered.user.id,sara.user.id); assert.equal((await call('/state', recovered.token)).data.debts[0].status,'confirmed');
  const secondDb = createApi(directory); assert.equal(secondDb.db.prepare('SELECT status FROM debts WHERE id=?').get(debt.id).status,'confirmed'); secondDb.db.close();
  // A claimed invitation can attach an existing account while keeping assignments intact.
  const invite = (await call('/friends', ali.token, { name:'Existing member' })).data;
  const another = newBill(ali.user.id); another.title='Next dinner'; another.participants.push(invite.person.id); another.items=[{ id:'pizza',name:'Pizza',quantity:1,unitPriceCents:10000,eligible:true,allocations:[{personId:invite.person.id,quantity:1}]}];
  const anotherSaved = (await call('/bills',ali.token,{bill:another})).data;
  assert.equal((await call(`/invite/${invite.inviteToken}/claim`,stranger.token,{})).status,200);
  const updated = (await call('/state',ali.token)).data.bills.find(x=>x.id===anotherSaved.id); assert.ok(updated.participants.includes(stranger.user.id)); assert.equal(calculate(updated).shares[stranger.user.id].total,10000);
});
