import test from 'node:test';
import assert from 'node:assert/strict';
import { calculate, distribute, newBill, validateBill, UNASSIGNED } from '../shared/calculations.js';
import { parseReceipt } from '../shared/parser.js';

function fixture() { const b = newBill('ali'); b.title = 'Dinner'; b.participants = ['ali','sara','hamza']; b.items = [{ id: 'food', name: 'Platters', quantity: 3, unitPriceCents: 800000, eligible: true, allocations: [{ personId: 'ali', quantity: 1 }, { personId: 'sara', quantity: 1 }, { personId: 'hamza', quantity: 1 }] }, { id: 'drinks', name: 'Drinks', quantity: 6, unitPriceCents: 100000, eligible: true, allocations: [{ personId: 'ali', quantity: 1 }, { personId: 'sara', quantity: 2 }, { personId: 'hamza', quantity: 3 }] }]; return b; }
test('50% on the first Rs 20k of a Rs 30k bill gives Rs 20k payable', () => { const b = fixture(); b.discount = { ...b.discount, type: 'percent', rate: 50, eligibleCapCents: 2000000 }; const r = calculate(b); assert.equal(r.subtotal, 3000000); assert.equal(r.discount, 1000000); assert.equal(r.total, 2000000); assert.equal(r.shares.ali.total, 600000); assert.equal(r.shares.sara.total, 666667); assert.equal(r.shares.hamza.total, 733333); assert.equal(r.complete, true); });
test('eligibility cap differs from savings cap and excluded items get no discount', () => { const b = fixture(); b.items[1].eligible = false; b.discount = { ...b.discount, type: 'percent', rate: 50, eligibleCapCents: 2000000, maxDiscountCents: 500000 }; const r = calculate(b); assert.equal(r.discount, 500000); assert.equal(r.total, 2500000); assert.equal(r.shares.ali.discount + r.shares.sara.discount + r.shares.hamza.discount, 500000); });
test('tax bases, manual override, and extra fees recalculate', () => { const b = fixture(); b.discount = { ...b.discount, type: 'percent', rate: 50, eligibleCapCents: 2000000 }; b.tax = { type: 'percent', rate: 10, amountCents: 0, basis: 'after' }; b.deliveryCents = 30000; assert.equal(calculate(b).total, 2230000); b.tax.basis = 'before'; assert.equal(calculate(b).total, 2330000); b.items[0].lineTotalCents = 2000000; assert.equal(calculate(b).subtotal, 2600000); });
test('unassigned and over-assigned units cannot finalize even when free', () => { const b = fixture(); b.items[1].allocations.pop(); assert.equal(calculate(b).unassigned, 300000); assert.equal(calculate(b).complete, false); b.discount = { ...b.discount, type: 'percent', rate: 100 }; assert.equal(calculate(b).unassigned, 0); assert.equal(calculate(b).complete, false); b.items[1].allocations[0].quantity = 10; assert.ok(calculate(b).errors.length); });
test('receipt mismatch requires explicit reconciliation', () => { const b = fixture(); b.receiptTotalCents = 3000050; assert.equal(calculate(b).complete, false); b.adjustmentCents = 50; b.adjustmentReason = 'Rounding'; assert.equal(calculate(b).complete, true); });
test('one shared item can have fractional quantities with exact money allocation', () => { const b = fixture(); b.items = [{ id: 'pizza', name: 'Pizza', quantity: 1, unitPriceCents: 10000, allocations: b.participants.map(personId => ({ personId, quantity: 1 / 3 })) }]; assert.equal(calculate(b).complete, true); assert.deepEqual(Object.values(calculate(b).shares).map(s => s.total), [3334,3333,3333,0]); });
test('largest-remainder distribution conserves every paisa over many bills', () => { for (let i = 1; i < 500; i++) { const a = distribute(i * 71, { a: i % 17, b: i % 7, c: i % 3, d: 3 }); assert.equal(Object.values(a).reduce((s,v) => s+v,0), i * 71); const b = fixture(); b.items[0].unitPriceCents = i * 31; b.discount = { ...b.discount, type: 'percent', rate: 17.5 }; b.tax = { ...b.tax, type: 'percent', rate: 7.5 }; b.deliveryCents = i; b.chargeSplit = i % 2 ? 'equal' : 'proportional'; const r = calculate(b); assert.equal(Object.values(r.shares).reduce((s,v) => s+v.total,0), r.total); } });
test('invalid prices, duplicate allocations, missing adjustment reasons are rejected', () => { const b = fixture(); b.items[0].unitPriceCents = NaN; assert.throws(() => validateBill(b)); b.items[0].unitPriceCents = 100; b.items[0].allocations.push({ personId: 'ali', quantity: 1 }); assert.throws(() => validateBill(b)); b.items[0].allocations.pop(); b.adjustmentCents = 1; assert.throws(() => validateBill(b)); });
test('parser extracts quantities, discount, tax and total without an LLM', () => { const p = parseReceipt('Dinner House\nBurger 2 x 850 1700\nCold Drink 6 x 200 1200\nDiscount 20% -580\nGST 348\nDelivery 150\nTotal 2818'); assert.equal(p.items.length,2); assert.equal(p.items[1].quantity,6); assert.equal(p.items[1].unitPriceCents,20000); assert.equal(p.charges.discountCents,58000); assert.equal(p.charges.taxCents,34800); assert.equal(p.receiptTotalCents,281800); });
test('parser preserves printed line total discrepancies for review', () => { const p = parseReceipt('2 Zinger Burger 850 1701\nTotal 1701'); assert.equal(p.items[0].quantity,2); assert.equal(p.items[0].lineTotalCents,170100); });
